version: "3.9"
services:
  web:
    build: .
    container_name: web
    hostname: web
    image: web:latest
    ports:
      - 3000:3000
    networks:
      - frontend
    restart: always
  postgres:
    container_name: postgres
    image: postgres:latest
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - common.env
    networks:
      - backend
    restart: always
  nginx:
    image: nginx:latest
    container_name: nginx
    hostname: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certs:/certs
      - /home/pi/github/valea-tocului/express.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frontend
      - backend
  certbot:
    image: certbot/dns-digitalocean:arm32v6-latest
    container_name: certbot
    hostname: certbot
    entrypoint: ["certbot", "certonly", "--config=/certbot/certbot.ini"] # --staging for testing
    volumes:
      - ./certbot:/certbot
      - ./certs:/etc/letsencrypt

networks:
  frontend:
    name: custom_frontend
  backend:
    name: custom_backend
